sudo: required
language: generic
services:
  - docker
env:
  global:
    - IMAGE_NAME=nfhbar/singletxmultisig
    - PACKAGE_VERSION=$(node -p "require('./package.json').version")

before_script:
  - docker pull "${IMAGE_NAME}" || true

install:
  - npm install -g truffle
  - npm install -g ganache-cli
  - npm install

script:
  - npm run lint
  - npm run ganache
  - sleep 5
  - truffle migrate
  - truffle test
  - npm run stop
  # - truffle networks --clean
  # - truffle publish
  # - sleep 60
  - docker build --pull --cache-from "${IMAGE_NAME}" --tag "${IMAGE_NAME}" .
  - docker run -e PACKAGE_VERSION "${IMAGE_NAME}"

after_script:
  - npm run coverage && cat coverage/lcov.info | coveralls
  - docker images

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  provider: script
  script: docker push "${IMAGE_NAME}"
  on:
    branch: master
