sudo: required

language: generic

services:
  - docker

before_script:
  - docker pull truffle/ci || true
  - docker pull trufflesuite/ganache-cli || true
  - docker pull codeclimate/codeclimate-eslint || true

script:
  - docker build --pull --cache-from truffle/ci --tag truffle/ci .
  - docker build --pull --cache-from trufflesuite/ganache-cli --tag trufflesuite/ganache-cli .
  - docker build --pull --cache-from codeclimate/codeclimate-eslint --tag codeclimate/codeclimate-eslint .
  - npm run lint
  - npm run ganache
  - sleep 5
  - truffle migrate
  - truffle test
  - npm run stop
after_script:
  - npm run coverage && cat coverage/lcov.info | coveralls
