sudo: required

language: generic

services:
  - docker

before_script:
  - env | grep -vE "^(RINKEBY_PRIVATE_KEY=$RINKEBY_PRIVATE_KEY)" > .env
  - docker pull nfhbar/singletxmultisig || true

script:
  - docker build --pull --cache-from nfhbar/singletxmultisig --tag nfhbar/singletxmultisig .
  - docker run --env-file ./env nfhbar/singletxmultisig

after_script:
  - npm run coverage && cat coverage/lcov.info | coveralls
  - docker images

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  provider: script
  script: docker push nfhbar/singletxmultisig
  on:
    branch: master
