sudo: required
language: generic
services:
  - docker
before_install:
  - docker pull truffle/ci
  - docker pull trufflesuite/ganache-cli
  - docker pull codeclimate/codeclimate-eslint

script:
  - npm run lint
  - npm run ganache
  - sleep 5
  - truffle migrate
  - truffle test
  - npm run stop
after_script:
  - npm run coverage && cat coverage/lcov.info | coveralls
